-- Extend and rename the shared category/transaction type enum to back the
-- unified Transactions model (INCOME | EXPENSE | TRANSFER).
ALTER TYPE "CATEGORY_TYPE_ENUM" RENAME VALUE 'ENTRY' TO 'INCOME';
ALTER TYPE "CATEGORY_TYPE_ENUM" RENAME VALUE 'OUTPUT' TO 'EXPENSE';
ALTER TYPE "CATEGORY_TYPE_ENUM" ADD VALUE IF NOT EXISTS 'TRANSFER';
ALTER TYPE "CATEGORY_TYPE_ENUM" RENAME TO "TRANSACTION_TYPE_ENUM";
